gcp_project_id              = "psi-de-0-sandbox-pjfc-poc"
gcp_region                  = "europe-west3"
gcp_zone                    = "europe-west3-a"
gcp_network                 = "vpc-ew3"
gcp_subnetwork              = "vpc-subnet-1-ew3"
gcp_cluster_name            = "pjfc"
gpc_nodepool_name           = "pjfc-nodepool"